[tool.poetry]
name = "gmail-ai-helper"
version = "0.1.0"
description = ""
authors = ["itai-melnik <itaimelnik@gmail.com>"]
readme = "README.md"
package-mode = false


[tool.poetry.dependencies]
python = "^3.12"
ollama = "^0.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
